name: Build and deploy 3.0/master.

on:
  push:
    branches: [ 3.0/paid-plugin ]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - uses: helsingborg-stad/municipio-deploy/3.0@master
  #     with:
  #       deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_KAMPANJ_HELSINGBORG_SE }}
  #       deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_KAMPANJ_HELSINGBORG_SE }}
  #       deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_KAMPANJ_HELSINGBORG_SE }}
  #       deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER }}
  #       deploy-host-user-key: ${{ secrets.DEPLOY_KEY }}
  #       deploy-host-web-server-user: ${{ secrets.WEB_SERVER_USER }}
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  #       acf-url: ${{ secrets.ACF_URL }}

  paid-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.PAID_PLUGINS_REPO }}
        token: ${{ secrets.HBG_GH_TOKEN }}

    - name: unzip and remove
      run: unzip * && rm *.zip && ls
      shell: bash

    # - name: The rsync deployment to www-data user.
    #   uses: burnett01/rsync-deployments@4.1
    #   with:
    #     switches: -avzrog --delete --backup --backup-dir=${{ inputs.deploy-host-backup-path }}/$GITHUB_SHA --chown=${{ inputs.deploy-host-web-server-user }}:${{ inputs.deploy-host-web-server-user }} --exclude config --exclude config-example --exclude wp-content/uploads --exclude wp-content/plugins/gravityforms --exclude wp-content/plugins/wp-schema-pro --exclude track-assets --exclude wp-content/plugins/volontar-wordpress --exclude wp-content/languages --exclude .htaccess --exclude wp-content/plugins/local_*
    #     path: .
    #     remote_path: ${{ inputs.deploy-host-path }}
    #     remote_host: ${{ inputs.deploy-host }}
    #     remote_user: ${{ inputs.deploy-host-user }}
    #     remote_key: ${{ inputs.deploy-host-user-key }}
    #     remote_port: ${{ inputs.deploy-host-port }}